http:
  routers:
    kuja7-web:
      rule: "Host(`kuja7.apps.evoxtechnologies.com`)"
      service: kuja7-web
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    kuja7-api:
      rule: "Host(`kuja7.api.evoxtechnologies.com`)"
      service: kuja7-api
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    kuja7-web:
      loadBalancer:
        servers:
          - url: "http://kuja7-web:80"

    kuja7-api:
      loadBalancer:
        servers:
          - url: "http://kuja7-api:3001"
